HTML = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>MyTradingBot</title>
<style>
:root{--bg:#090d12;--card:#121820;--line:#202a35;--text:#f2f5f8;--muted:#8b98a8;--blue:#3388ff;--green:#19d66b;--red:#ff4d67}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif}
.app{max-width:720px;margin:auto;min-height:100vh;padding:18px 16px 100px}header{display:flex;justify-content:space-between;align-items:center;margin:6px 2px 20px}h1{font-size:28px;margin:0}.sub{font-size:12px;color:var(--muted);margin-top:3px}.dot{width:9px;height:9px;border-radius:50%;background:var(--green);display:inline-block;margin-right:7px;box-shadow:0 0 12px var(--green)}
.card{background:linear-gradient(145deg,#141b24,#10161d);border:1px solid var(--line);border-radius:18px;padding:16px;margin:10px 0;box-shadow:0 8px 25px #0003}.hero{display:grid;grid-template-columns:1fr 1fr;gap:10px}.metric{font-size:26px;font-weight:750;margin-top:7px}.label{color:var(--muted);font-size:13px}
.section{display:flex;justify-content:space-between;align-items:center;margin:22px 3px 8px}.section h2{font-size:18px;margin:0}.badge{font-size:11px;border-radius:20px;padding:5px 8px;background:#1c2631;color:#aeb9c5}
.op{padding:14px 0;border-top:1px solid var(--line)}.op:first-child{border-top:0}.row{display:flex;justify-content:space-between;gap:12px;align-items:center}.symbol{font-weight:750}.side{font-weight:800}.long{color:var(--green)}.short{color:var(--red)}.meta{display:flex;gap:10px;color:var(--muted);font-size:11px;margin-top:7px;flex-wrap:wrap}
.btn{border:0;border-radius:12px;padding:11px 14px;background:var(--blue);color:#fff;font-size:14px;font-weight:650}.btn.secondary{background:#1d2732}.btn.danger{background:#2b1720;color:#ff7185}.trade{display:flex;justify-content:space-between;align-items:center;gap:12px}.tradeBtn{min-width:150px;border:0;border-radius:13px;padding:13px 15px;color:#fff;font-size:14px;font-weight:750}.tradeOn{background:#158a49}.tradeOff{background:#26313d}
.nav{position:fixed;left:50%;transform:translateX(-50%);bottom:0;width:min(720px,100%);padding:9px 8px calc(9px + env(safe-area-inset-bottom));background:#0d1218ee;backdrop-filter:blur(18px);border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(5,1fr);z-index:10}.nav button{background:none;border:0;color:var(--muted);font-size:10px;padding:7px 2px}.nav button.active{color:#fff}.ico{display:block;font-size:19px;margin-bottom:2px}.page{display:none}.page.active{display:block}
input,select{width:100%;background:#0d131a;color:#fff;border:1px solid #293541;border-radius:11px;padding:12px;margin-top:6px;font-size:15px}.form{display:grid;gap:12px}.two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.empty{text-align:center;color:var(--muted);padding:28px 10px}.tiny{font-size:11px;color:var(--muted)}
</style>
</head>
<body>
<div class="app">
<header><div><h1>MyTradingBot</h1><div class="sub"><span class="dot"></span><span id="mode">PAPER MODE</span></div></div><button class="btn secondary" onclick="refreshAll()">↻</button></header>
<section id="home" class="page active">
<div class="hero"><div class="card"><div class="label">Баланс</div><div class="metric" id="balance">$1,000</div></div><div class="card"><div class="label">Сегодня PnL</div><div class="metric" id="pnl">$0.00</div></div></div>
<div class="card"><div class="row"><div><div class="label">Двигатель</div><div class="metric" id="engine">Запуск…</div></div><div class="badge" id="scan">SCAN</div></div></div>
<div class="card trade"><div><div class="label">Торговля</div><div class="tiny" id="tradeHint">Сканирование работает независимо</div></div><button id="tradeBtn" class="tradeBtn tradeOff" onclick="toggleTrading()">▶ Запустить</button></div>
<div class="section"><h2>Возможности</h2><span class="badge" id="oppCount">0</span></div><div class="card" id="opps"><div class="empty">Ищу рынок…</div></div>
</section>
<section id="markets" class="page"><div class="section"><h2>Markets</h2><span class="badge">Bybit Linear</span></div><div id="marketsList" class="card"><div class="empty">Загрузка рынков…</div></div></section>
<section id="positions" class="page"><div class="section"><h2>Positions</h2><span class="badge" id="posCount">0 / 3</span></div><div id="positionsList" class="card"><div class="empty">Открытых позиций нет</div></div></section>
<section id="stats" class="page"><div class="section"><h2>Stats</h2><span class="badge">Last 20</span></div><div class="hero"><div class="card"><div class="label">Сделки</div><div class="metric" id="trades">0</div></div><div class="card"><div class="label">Win rate</div><div class="metric" id="winrate">—</div></div></div><div class="card" id="history"><div class="empty">История пока пуста</div></div></section>
<section id="settings" class="page"><div class="section"><h2>Settings</h2><span class="badge">PAPER</span></div>
<div class="card form"><div><label class="label">Бюджет USDT</label><input id="budget" type="number" min="1" step="1"></div>
<div class="two"><div><label class="label">Плечо</label><select id="lev"><option>1</option><option>2</option><option>3</option><option>5</option><option>10</option><option>20</option></select></div><div><label class="label">Количество TP</label><select id="tp"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></div></div>
<div><label class="label">Одновременных позиций</label><select id="maxpos"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></div><button class="btn" onclick="saveSettings()">Сохранить настройки</button><div class="tiny">Размер позиции рассчитывается автоматически от риска и расстояния до SL. Реальные ордера пока отключены.</div></div>
<div class="card"><button class="btn danger" onclick="resetBot()">Сбросить PAPER-статистику</button></div></section>
</div>
<nav class="nav"><button class="active" onclick="tab('home',this)"><span class="ico">⌂</span>Home</button><button onclick="tab('markets',this)"><span class="ico">◫</span>Markets</button><button onclick="tab('positions',this)"><span class="ico">◈</span>Positions</button><button onclick="tab('stats',this)"><span class="ico">▥</span>Stats</button><button onclick="tab('settings',this)"><span class="ico">⚙</span>Settings</button></nav>
<script>
const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}const $=id=>document.getElementById(id);
async function api(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function tab(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(id==='markets')loadMarkets();if(id==='positions')loadPositions();if(id==='stats')loadStats();if(id==='settings')loadSettings()}
function fmt(n,d=2){return Number(n||0).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d})}
async function loadHome(){try{const[h,o,p,s]=await Promise.all([api('/health'),api('/api/opportunities'),api('/api/positions'),api('/api/settings')]);$('balance').textContent='$'+fmt(s.budget,2);window.maxPos=s.max_positions;$('engine').textContent=h.running?'ONLINE':'OFFLINE';$('tradeBtn').textContent=h.trading_enabled?'■ Остановить':'▶ Запустить';$('tradeBtn').className='tradeBtn '+(h.trading_enabled?'tradeOn':'tradeOff');$('tradeHint').textContent=h.trading_enabled?'Торговля разрешена (PAPER)':'Сигналы ищутся, входы отключены';$('mode').textContent=(h.mode||'paper').toUpperCase()+' MODE';$('oppCount').textContent=o.length;$('posCount').textContent=p.length+' / '+(window.maxPos||3);$('scan').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('opps').innerHTML=o.length?o.slice(0,8).map((x,i)=>'<div class="op"><div class="row"><div><span class="symbol">'+x.symbol+'</span> <span class="side '+x.side.toLowerCase()+'">'+x.side+'</span></div><button class="btn" onclick="openPos('+i+')">Войти</button></div><div class="meta"><span>'+x.regime+'</span><span>'+x.setup+'</span><span>conf '+(x.confidence*100).toFixed(0)+'%</span><span>move '+(x.expected_move*100).toFixed(2)+'%</span></div><div class="meta"><span>Entry '+fmt(x.entry,6)+'</span><span>SL '+fmt(x.stop_loss,6)+'</span><span>TP1 '+fmt(x.take_profits[0],6)+'</span></div></div>').join(''):'<div class="empty">Подходящих входов сейчас нет.<br>Двигатель продолжает сканирование.</div>'}catch(e){$('engine').textContent='OFFLINE';$('opps').innerHTML='<div class="empty">Сервис перезапускается…<br><span class="tiny">Обнови через несколько секунд.</span></div>'}}
async function toggleTrading(){try{const h=await api('/health');await api('/api/trading',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!h.trading_enabled})});await loadHome()}catch(e){alert('Сервис пока недоступен')}}
async function openPos(i){const r=await api('/api/paper/open/'+i,{method:'POST'});if(r.error){alert('Не удалось открыть: '+r.error);return}await loadHome();await loadPositions()}
async function loadMarkets(){try{const m=await api('/api/markets');if(!Array.isArray(m))throw new Error('bad market response');$('marketsList').innerHTML=m.slice(0,60).map(x=>'<div class="op"><div class="row"><span class="symbol">'+x.symbol+'</span><span class="'+(x.change_24h>=0?'long':'short')+'">'+x.change_24h.toFixed(2)+'%</span></div><div class="meta"><span>$'+fmt(x.last,6)+'</span><span>24h $'+(x.turnover_24h/1e6).toFixed(1)+'M</span><span>spread '+x.spread_bps.toFixed(1)+'bps</span></div></div>').join('')||'<div class="empty">Рынки пока не получены. Двигатель продолжает загрузку.</div>'}catch(e){$('marketsList').innerHTML='<div class="empty">Рынки не загрузились.<br><span class="tiny">Проверь через несколько секунд или нажми ↻.</span></div>'}}
async function loadPositions(){try{const p=await api('/api/positions');$('posCount').textContent=p.length+' / '+(window.maxPos||3);$('positionsList').innerHTML=p.length?p.map(x=>'<div class="op"><div class="row"><div><span class="symbol">'+x.symbol+'</span> <span class="side '+x.side.toLowerCase()+'">'+x.side+'</span></div><button class="btn danger" onclick="closePos(\''+x.id+'\')">Закрыть</button></div><div class="meta"><span>Entry '+fmt(x.entry,6)+'</span><span>Qty '+fmt(x.quantity,4)+'</span><span>Lev '+x.leverage+'x</span><span class="'+(x.pnl>=0?'long':'short')+'">PnL $'+fmt(x.pnl)+'</span></div><div class="meta"><span>SL '+fmt(x.stop_loss,6)+'</span><span>TP: '+x.take_profits.map(v=>fmt(v,6)).join(' / ')+'</span></div></div>').join(''):'<div class="empty">Открытых позиций нет</div>'}catch(e){$('positionsList').innerHTML='<div class="empty">Позиции пока недоступны</div>'}}
async function closePos(id){await api('/api/positions/'+id+'/close',{method:'POST'});loadPositions();loadStats();loadHome()}
async function loadStats(){try{const h=await api('/api/history');const wins=h.filter(x=>Number(x.pnl)>0).length;$('trades').textContent=h.length;$('winrate').textContent=h.length?Math.round(wins/h.length*100)+'%':'—';$('history').innerHTML=h.length?h.map(x=>'<div class="op"><div class="row"><span class="symbol">'+x.symbol+' '+x.side+'</span><span class="'+(x.pnl>=0?'long':'short')+'">$'+fmt(x.pnl)+'</span></div><div class="meta"><span>'+x.reason+'</span><span>'+new Date(x.closed_at).toLocaleString()+'</span></div></div>').join(''):'<div class="empty">История пока пуста</div>'}catch(e){}}
async function saveSettings(){try{const data={budget:Number($('budget').value),leverage:Number($('lev').value),take_profits:Number($('tp').value),max_positions:Number($('maxpos').value)};const r=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});window.maxPos=r.max_positions;alert('Настройки сохранены');loadHome()}catch(e){alert('Не удалось сохранить настройки')}}
async function loadSettings(){try{const r=await api('/api/settings');$('budget').value=r.budget;$('lev').value=r.leverage;$('tp').value=r.take_profits;$('maxpos').value=r.max_positions;window.maxPos=r.max_positions}catch(e){}}
async function resetBot(){if(!confirm('Сбросить PAPER-позиции и статистику?'))return;await api('/api/reset',{method:'POST'});loadHome();loadPositions();loadStats()}
async function refreshAll(){await loadHome();if($('markets').classList.contains('active'))loadMarkets();if($('positions').classList.contains('active'))loadPositions();if($('settings').classList.contains('active'))loadSettings()}
loadSettings();loadHome();loadStats();setInterval(refreshAll,5000);
</script>
</body>
</html>'''
